### ISSUE TITLE
Failed to build due to deprecated

### ISSUE THREAD

**Issue by rohitjoshi** [carllerche/curl-rust#54]
/rust/curl-rust/src/lib.rs:8:14: 8:36 error: #[phase] is deprecated; use #[macro_use], #[plugin], and/or #    [no_link]
    rust/curl-rust/src/lib.rs:8 #[cfg(test)] #[phase(plugin, link)] extern crate log;

    rust/curl-rust/src/ffi/opt.rs:4:5: 4:23 error: unresolved import `std::c_str::ToCStr`. Could not find `c_str` in `std`
    rust/curl-rust/src/ffi/opt.rs:4 use std::c_str::ToCStr;
                                                           ^~~~~~~~~~~~~~~~~~
    rust/curl-rust/src/ffi/easy.rs:4:5: 4:21 error: unresolved import `std::c_vec::CVec`. Could not find `c_vec` in `std`
    rust/curl-rust/src/ffi/easy.rs:4 use std::c_vec::CVec;
                                                            ^~~~~~~~~~~~~~~~
    rust/curl-rust/src/ffi/err.rs:1:5: 1:24 error: unresolved import `std::c_str::CString`. Could not find `c_str` in `std`
    rust/curl-rust/src/ffi/err.rs:1 use std::c_str::CString;
                                                           ^~~~~~~~~~~~~~~~~~~

**Comment by alexcrichton** [comment]
Fixed in https://github.com/carllerche/curl-rust/pull/53
