### ISSUE TITLE
Test instability - Errant Connections closed during tests

### ISSUE THREAD

**Issue by posix4e** [carllerche/curl-rust#79]
I ran

 export BROKE=true;while $BROKE; do cargo test test_post::test_post_binary_with_reader || BROKE=false ;done 

in a couple of terminals. It got the following errors (after a bunch of tries)

running 2 tests
*** Error in `/home/posix4e/projects/curl-rust/target/debug/test-33ef6bd56fa132ca': double free or corruption (fasttop): 0x00007ff64000cd30 ***
Process didn't exit successfully: `/home/posix4e/projects/curl-rust/target/debug/test-33ef6bd56fa132ca test_post::test_post_binary_with_reader` (signal: 6)
posix4e@posix4e-P27GV2:~/projects/curl-rust$ ^C
posix4e@posix4e-P27GV2:~/projects/curl-rust$ export BROKE=true;while $BROKE; do cargo test test_post::test_post_binary_with_reader || BROKE=false ;done

or 
running 2 tests
test test_post::test_post_binary_with_reader ... FAILED
test test_post::test_post_binary_with_reader_and_content_length ... ok

failures:

---- test_post::test_post_binary_with_reader stdout ----
        thread 'test_post::test_post_binary_with_reader' panicked at 'called `Result::unwrap()` on an `Err` value: Failed sending data to the peer', src/libcore/result.rs:731

**Comment by posix4e** [comment]
I was able to reproduce this by running
posix4e@posix4e-P27GV2:~$ cat /dev/zero | pigz -c > baz 
in one thread (so cpu is blocked) 

and one instance of the above while loop.Both errors appeared. This makes me think we have timing problem.

**Comment by carllerche** [comment]
There are a bunch of timeout settings that may be too aggressive on travis.

**Comment by posix4e** [comment]
This actually happens on my local machine. The double free is very worrisome

**Comment by posix4e** [comment]
Here's the backtrace
failures:

---- test_post::test_post_binary_with_reader stdout ----
        thread 'test_post::test_post_binary_with_reader' panicked at 'called `Result::unwrap()` on an `Err` value: Failed sending data to the peer', src/libcore/result.rs:731

stack backtrace:
   1:     0x7f10b72ff15e - sys::backtrace::write::h5459bb2971e2d13csrs
   2:     0x7f10b73026d4 - panicking::on_panic::h1224c257bc6b0ee0mdx
   3:     0x7f10b72f2cde - rt::unwind::begin_unwind_inner::h50e46633c2b0947f0Sw
   4:     0x7f10b72f36cc - rt::unwind::begin_unwind_fmt::h704aa2e2b6a491446Rw
   5:     0x7f10b7302356 - rust_begin_unwind
   6:     0x7f10b7339c04 - panicking::panic_fmt::hc9237b7ecab48700neC
   7:     0x7f10b71e9ba0 - result::Result<T, E>::unwrap::h16765852106829500353
                        at src/libcore/macros.rs:28
   8:     0x7f10b71ef765 - test_post::test_post_binary_with_reader::h55c5ce4a345474faT2a
                        at test/test_post.rs:72
   9:     0x7f10b72d01eb - boxed::F.FnBox<A>::call_box::h17330699656030899451
  10:     0x7f10b72d2e32 - boxed::F.FnBox<A>::call_box::h15359364645883528207
  11:     0x7f10b72d09b9 - rt::unwind::try::try_fn::h6782072943666172489
  12:     0x7f10b73078f8 - rust_try_inner
  13:     0x7f10b73078e5 - rust_try
  14:     0x7f10b72fcfd7 - rt::unwind::try::inner_try::hf4754302de4d128bTOw
  15:     0x7f10b72d0bcb - boxed::F.FnBox<A>::call_box::h6199879319121485493
  16:     0x7f10b7301491 - sys::thread::Thread::new::thread_start::h7bc5208573aad01aGYv
  17:     0x7f10b5bdc0a4 - start_thread
  18:     0x7f10b63f5cfc - clone
  19:                0x0 - <unknown>


failures:
    test_post::test_post_binary_with_reader

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', src/libtest/lib.rs:254
stack backtrace:
   1:     0x7f10b72ff15e - sys::backtrace::write::h5459bb2971e2d13csrs
   2:     0x7f10b7302965 - panicking::on_panic::h1224c257bc6b0ee0mdx
   3:     0x7f10b72f2cde - rt::unwind::begin_unwind_inner::h50e46633c2b0947f0Sw
   4:     0x7f10b72af721 - rt::unwind::begin_unwind::h6388588896502290535
   5:     0x7f10b72b11ec - test_main::h7538f84cc706d3ecI1a
   6:     0x7f10b72b79e2 - test_main_static::h096611c4ce100a90d4a
   7:     0x7f10b71f2a8c - __test::main::h36e46bef2358955bTab
   8:     0x7f10b73078f8 - rust_try_inner
   9:     0x7f10b73078e5 - rust_try
  10:     0x7f10b7304498 - rt::lang_start::hdad930ec0565e764j8w
  11:     0x7f10b71f2c0b - main
  12:     0x7f10b631dec4 - __libc_start_main
  13:     0x7f10b71a60b8 - <unknown>
  14:                0x0 - <unknown>

posix4e@posix4e-P27GV2:~/projects/curl-ru

**Comment by posix4e** [comment]
Sorry for all the spam. Other info, when verbose is enabled
<
* Excess found in a non pipelined read: excess = 4, size = 5, maxdownload = 5, bytecount = 0
* Send failure: Connection reset by peer
We see this

**Comment by posix4e** [comment]
Interestingly only the test without  content length seems to crash

**Comment by posix4e** [comment]
The one common attribute is if you add a .verbose() to the handler you see a connection closed error. Something is closing it's socket before it's done.

**Comment by carllerche** [comment]
I managed to figure it out: https://travis-ci.org/carllerche/curl-rust

It was an issue with older versions of libcurl (including the one that travis uses) did not dedup the content-length header.
