### ISSUE TITLE
libcurl errors with latests Xcode Command Line Tools

### ISSUE THREAD

**Issue by wagenet** [carllerche/curl-rust#87]
`A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision`
See https://github.com/skylightio/skylight-ruby/issues/46

I'm not a Rust guy so I may be incorrect about this being a curl-rust issue.

**Comment by alexcrichton** [comment]
Thanks for the report! We actually [ran into this in Cargo](https://github.com/rust-lang/cargo/issues/1937) as well (Rust's package manager) and I think I've actually [fixed this](https://github.com/carllerche/curl-rust/commit/b4cb511d50f4dabce9fe5ea1d0112c34868b0923) in the 0.2.11 release of this library. I'll post on the skylight-ruby issue about this though mentioning that an upgrade should fix the issue.

**Comment by wagenet** [comment]
Thanks!
